### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by ShahierNashaat** [ShahierNashaat/ruby-capstone#38]
- [project link](https://github.com/ShahierNashaat/ruby-capstone/projects/1)
- Three members in the group
- Team Member 1: [ShahierNashaat](https://github.com/ShahierNashaat)
- Team Member 2: [Somdotta07](https://github.com/Somdotta07)
- Team Member 3:[ Wes-Isaac](https://github.com/Wes-Isaac)

**Comment by hiromataba** [comment]
Hi :wave: :wave: @ShahierNashaat, @Wes-Isaac and @Somdotta07  

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif) 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
